print("\n")
print("     ,     ,")
print("    (\____/)")
print("     (_oo_)")
print("       (O)")
print("     __||__    \)")
print("  []/______\[] /")
print("  / \______/ \/")
print(" /    /__\")
print("(\   /____\")
print("\n")
print(" Hello world!!")
print("\n")
